server-configs:
  exchange-trading-data-provider:
    twelve:
      api-key: ${TWELVE_API_KEY}
      base-url: ${TWELVE_BASE_URL}
      rate-exchange-path: currency_conversion
  rest-service:
    web-client:
      response-timeout: 8
  month-limit:
    defaultLimitNumber: ${SERVER_CONFIGS_DEFAULT_LIMIT}

spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:bank_microservice}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:user}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.H2Dialect}org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    sql: debug
    web: debug
