name: build_workflow

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        id: step1
        run: |
          modules=$(find . -type f -name pom.xml -exec dirname {} \;)

          # Собираем образы для каждого модуля
          for module in $modules; do
            mvn clean -Dmaven.test.skip package
          
            module_name='bank_microservice'
            docker build -t $module_name $module
          
            githubBranchName=${GITHUB_REF_NAME}
          
            if [ ${GITHUB_EVENT_NAME} == 'pull_request' ]; then
              githubBranchName=${GITHUB_HEAD_REF}
            fi
          
            git_hash=$(git rev-parse --short ${GITHUB_SHA})
          
            docker tag $module_name ${{ secrets.DOCKER_USERNAME }}/$module_name:$githubBranchName-$git_hash
            docker push ${{ secrets.DOCKER_USERNAME }}/$module_name:$githubBranchName-$git_hash
          
            if [ ${GITHUB_REF} = 'refs/heads/main' ]; then
              docker tag proga ${{ secrets.DOCKER_USERNAME }}/$module:latest
              docker push ${{ secrets.DOCKER_USERNAME }}/$module:latest
            fi
          done